### PR TITLE
CLOUDP-110989: Adds OnResponseProcessed

### PR DESCRIPTION
**Pull request by fmenezes**
## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.

Added a `OnResponseProcessed` for logging purposes

Link to any related issue(s): [CLOUDP-110989](https://jira.mongodb.org/browse/CLOUDP-110989)

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Review by gssbzn — COMMENTED** [review]
Given you are changing an exported function this is a breaking change, could we make this a non breaking change?

The other thing, I'm finding having both `onRequestCompleted` and `onAfterRequestCompleted` confusing, is there a better name for `onAfterRequestCompleted`? `onResponseProcessed` or similar?

**Comment by fmenezes** [comment]
@gssbzn as mentioned offline this change will most likely be more beneficial to keep on a breaking change

**Comment by fmenezes** [comment]
@themantissa please tag terraform team as reviewers

**Review by gssbzn — APPROVED** [review]
LGTM

**Review by evertsd — APPROVED** [review]
LGTM, does not look like this "breaking" change will affect `terraform-provider-mongodbatlas`

**Pull request merged**
