### PR TITLE
test: move from travis to github actions

### PR DESCRIPTION
**Pull request by gssbzn**
## Description

Recently travis has become really slow to start so let's try moving to github actions

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Review by andreaangiolillo — APPROVED** [review]
LGTM. Happy to try github actions 👍

**Review by themantissa — APPROVED** [review]
LGTM, Travis has been a bit painful for sure lately.   @coderGo93 or @leofigy can one of you chime in if you are okay w/ this change to github actions?

**Review by coderGo93 — APPROVED** [review]
Kinda different from TF repo(in .yml), but it seems it does the same job as travis so LGTM!!!

**Review by leofigy — APPROVED** [review]
LGTM :)

**Pull request merged**
