### PR TITLE
feat: move cloud provider regions method to cluster

### PR DESCRIPTION
**Pull request by gssbzn**
## Description

Docs are in for the cloud provider regions it should be in the same group as all cluster methods

This may be a breaking change but since we have not released a client I'm ok with this change

Link to any related issue(s): 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Comment by gssbzn** [comment]
@themantissa ready for you

**Review by themantissa — APPROVED** [review]
LGTM - we aren't using the cloud provider regions method yet in the provider but since it is moving into cluster would like a review from DoU so added both @leofigy and @coderGo93 for visibility and double check.

**Review by leofigy — APPROVED** [review]
LGTM since is just adding a new method in the interface.

**Pull request merged**
