### PR TITLE
INTMDB-171: [Atlas Go Client] Release a new version

### PR DESCRIPTION
**Pull request by gssbzn**
## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Review by themantissa — DISMISSED** [review]
LGTM!  Thank you!

**Comment by gssbzn** [comment]
Holding on this seems we have a couple of PRs we should include in the release #177 and #178

**Comment by themantissa** [comment]
@gssbzn both PRs are merged so we should be good to go.  Thanks!

**Review by themantissa — APPROVED** [review]
LGTM!  Thank you :)

**Pull request merged**
