### PR TITLE
INTMDB-138: Release preparation

### PR DESCRIPTION
**Pull request by gssbzn**
## Description

Update CHANGELOG

### CODE REVIEW

**Comment by drewrothstein** [comment]
Will this include https://github.com/mongodb/go-client-mongodb-atlas/pull/139 ?

Thank you-

**Review by themantissa — APPROVED** [review]
LGTM - will add DoU devs for a quick check and fyi (@leofigy and @coderGo93 )

**Comment by themantissa** [comment]
@drewrothstein  #139 was in v0.5.0.  Thanks!

**Review by coderGo93 — APPROVED** [review]
LGTM

**Pull request merged**
