### PR TITLE
INTMDB-19: Added fields in datalake databases and stores

### PR DESCRIPTION
**Pull request by coderGo93**
## Description

- Added field `AdditionalStorageClasses` for `DataLakeStore`
- Added field `MaxWildcardCollections`  for `DataLakeDatabase`

Link to any related issue(s): 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Review by gssbzn — APPROVED** [review]
LGTM but I'm not seeing these fields on our [docs](https://docs.mongodb.com/datalake/reference/api/datalakes-api/) assuming they are just undocumented

**Comment by coderGo93** [comment]
Hi @gssbzn , the docs comes from [here](https://docs.mongodb.com/datalake/reference/format/data-lake-configuration/#example-configuration-for-individual-data-stores)

**Comment by gssbzn** [comment]
> Hi @gssbzn , the docs comes from here

oh I didn't know that one, can you please add a link to that docs on the field?

**Review by gssbzn — APPROVED** [review]
Thanks 💯

**Review by abner-dou — APPROVED** [review]
LGTM!

**Pull request merged**
