### PR TITLE
Fix cluster struct to allow pasue/start a cluster

### PR DESCRIPTION
**Pull request by gssbzn**
## Proposed changes

**Breaking change**

Currently if you want to pause or restart a cluster you can only send the `Paused` property and nothing else or you'll get errors like "Can't pause and update a cluster at the same time"

Having some internal structs as non-pointers were making go serialize them so we could never do this kind of operation

Sadly this may be a breaking change as we are changing the type of the struct and those depending on it may need to update after this change

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Comment by gssbzn** [comment]
@themantissa tagging you in advance as this may be a breaking change but sadly is a bug that we may need to fix sooner than later (this came from a customer that wants to pause/restart clusters with the cli)

**Comment by themantissa** [comment]
Thank you for the alert @gssbzn - makes sense for the CLI.  We haven't yet supported in Terraform since Atlas auto unpauses, which doesn't quite mesh w/ the Terraform philosophy.

@PacoDw and @marinsalinas (and @thetonymaster) I assume this will impact both Terraform and CloudFormation so we'll need to schedule the work to coordinate with the next release of the go-client?

**Comment by PacoDw** [comment]
yes @themantissa, it will, but it won't be a breaking change for terraform

**Comment by themantissa** [comment]
@PacoDw can you also just submit a review?

**Comment by gssbzn** [comment]
Thank yall for the review

**Pull request merged**
