### PR TITLE
feat: remove project whitelist

### PR DESCRIPTION
**Pull request by gssbzn**
## Description

These endpoints will be removed next week so removing the code here

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Comment by gssbzn** [comment]
@themantissa not sure if terraform hasn't updated yet but this change will make it urgent for people to update

**Comment by leofigy** [comment]
AFAIK Not yet :)

**Comment by themantissa** [comment]
Yup, we will be deprecating this in the next Terraform version (will create the ticket soon) but we missed our timing as Atlas is actually turning off this endpoints in June (pretty soon).  So that will force the change too for new and old downstream tools.

**Review by themantissa — APPROVED** [review]
LGTM, thank you!

**Comment by themantissa** [comment]
INTMDB-212 for Terraform

**Pull request merged**
