### PR TITLE
CLOUDP-132512: [Atlas CLI] Add support for updating a serverless cluster

### PR DESCRIPTION
**Pull request by gssbzn**
## Description

CLOUDP-132512

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Required Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Review by blva — APPROVED** [review]
LGTM

**Comment by gssbzn** [comment]
@themantissa this may need a review from the TF team

**Review by tibulca — APPROVED** [review]

**Comment by themantissa** [comment]
@evertsd and @martinstibbe added you both to see which wants to take on the review here and if it's a breaking change let me know.   This adds the functionality for https://jira.mongodb.org/browse/INTMDB-363, which we will do for 1.5.0.

**Review by themantissa — APPROVED** [review]
LGTM, added Akava dev for a review in regard to Terraform.

**Review by evertsd — APPROVED** [review]
From what I can tell, this should be fine on the terraform provider end.

Once we upgrade the version of go client it uses though, we'll want to provide the ability to specify `ServerlessBackupOptions` when creating a serverless resource.

TL:DR; LGTM

**Pull request merged**
