### PR TITLE
chore: Updates to Go 1.20 and creates .tool-versions

### PR DESCRIPTION
**Pull request by lantoli**
## Description

Creates .tool-versions for Go 1.18

Link to any related issue(s): 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Required Checklist:

- [X] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run `make fmt` and formatted my code

### CODE REVIEW

**Comment by wtrocki** [comment]
[question] Go 1.18 is the minimal version we support (in practice it should be 1.20 as we support the latest 2 major releases)
Any reason not to use the latest?

**Comment by wtrocki** [comment]
Nothing blocking merge. Just question about the intentions.

**Comment by lantoli** [comment]
> [question] Go 1.18 is the minimal version we support (in practice it should be 1.20 as we support the latest 2 major releases) Any reason not to use the latest?

@wtrocki Using the same version in go.mod .  I didn't want to update the version in case it affected other pipelines.

If you think it doesn't affect I can upgrade to 1.20

**Comment by lantoli** [comment]
@wtrocki  in Release GH action also 1.18 is being used (release-check.yml)

**Review by gssbzn — COMMENTED** [review]
we follow the go support so at this point 1.20 would be the minimum supported

**Pull request merged**
